USE bc_server_db;

CREATE TABLE custom_signal_u16_info
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	mtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	permission TINYINT UNSIGNED NOT NULL DEFAULT 0,
	min_val SMALLINT UNSIGNED NOT NULL DEFAULT 65535, /* 0xFFFF */
	max_val SMALLINT UNSIGNED NOT NULL DEFAULT 65535, /* 0XFFFF */
	def_val SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	
	en_statistics BOOLEAN NOT NULL DEFAULT TRUE,
	custom_signal_id INT UNSIGNED NOT NULL,

	UNIQUE INDEX i_custom_signal_id(custom_signal_id)
);
