USE bc_server_db;

CREATE TABLE sn_info
(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	mtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	sn CHAR(64) NOT NULL,
	develop_user_id BIGINT UNSIGNED NOT NULL,
	
	activite_date DATE NOT NULL DEFAULT 0,
	expired_date DATE NOT NULL DEFAULT 0,
	
	UNIQUE INDEX i_sn(sn), 
	INDEX i_develop_user_id(develop_user_id)
);